version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
    - "3306:3306"
    volumes:
      - "neurotech_data:/var/lib/mysql"

volumes:
  neurotech_data: